name: Python CI actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
    #  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres        
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Create test database
      run: |
        echo ${POSTGRES_HOST}
        echo ${POSTGRES_PASSWORD}
        psql -c 'create database test;' -U postgres -h localhost
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip
        pip install -U -r requirements.txt
        pip install -U -r dev-requirements.txt

    - name: Test with pytest
      run: |
        pytest
